environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON: python2
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      PYTHON: python2
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON: python3
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      PYTHON: python3

build_script:
  - IF NOT %MSYSTEM% == "" set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - IF NOT %MSYSTEM% == "" set CHERE_INVOKING=yes
  - IF NOT %MSYSTEM% == "" bash -lc "bash .appveyor/msys2.sh"

deploy: off
