matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "2.7"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.3"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.4"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.5"
      env: CFLAGS="-std=c90 -pedantic -Wno-long-long -Werror"
    - os: linux
      dist: trusty
      language: python
      python: "3.6"

install:
  - travis_retry sudo apt-get update -q
  - travis_retry sudo apt-get install -y libcairo2-dev
  - python -m pip install --upgrade pytest flake8 sphinx sphinx_rtd_theme

script:
  - python setup.py test
  - python -m flake8 .
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.3" ]; then python -m sphinx -W -a -E -b html -n docs docs/_build; fi
